### PR TITLE
lara_control: reset rotation when dismounting vehicle

### LINKED ISSUE #275: TR2X bug: Lara's posture changes when teleporting off a boat/skidoo while on a slope
**Regression since:** [0.3](https://github.com/LostArtefacts/TR2X/releases/tag/0.3)
(Lara doesn't teleport off a boat/skidoo in 0.2.)

________________________

**Steps to reproduce:**

1. `/play 11`
2. `/tp red`
3. Move the skidoo so it's on a slope facing up
4. `/tp 12`

Screenshot

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #275.

### CODE REVIEW

**Review by aredfan — APPROVED** [review]

**Review by walkawayy — APPROVED** [review]

File: src/game/lara/cheat.c [hunk 1]
```diff
@@ -374,7 +374,11 @@ bool Lara_Cheat_Teleport(int32_t x, int32_t y, int32_t z)
         g_Lara.gun_status = LGS_ARMLESS;
     }
 
-    Lara_GetOffVehicle();
+    if (g_Lara.skidoo != NO_ITEM) {
+        Lara_GetOffVehicle();
+        g_LaraItem->rot.x = 0;
+        g_LaraItem->rot.z = 0;
```
Comment (rr-) [inline src/game/lara/cheat.c]: I believe the new assignments would best belong inside `Lara_GetOffVehicle`. Additionally, since the check is already done within the function, it can be safely omitted.

Comment (lahm86) [reply src/game/lara/cheat.c]: Thanks, I've moved it into that function instead. Everything looks OK to me when dismounting vehicles normally, but would appreciate a second glance.

**Review by aredfan — APPROVED** [review]

**Review by rr- — APPROVED** [review]

**Review by walkawayy — APPROVED** [review]
